### model
model_name_or_path: Qwen/Qwen3-4B
# model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
template: qwen3

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# dataset: stop_predictor_dpo
# dataset: stop_predictor_dpo_no_early_stop_rejected_sample
dataset: omr_qwen3_4b_evaltree_1K_temp1_w_evaltree_depth_0_3
# template: None
cutoff_len: 8192
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output
output_dir: saves/qwen3_4B/sft_evaltree_omr_1k_temp1_w_evaltree_depth_0_3
logging_steps: 1
save_steps: 10000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### sequence parallel
sequence_parallel_size: 4
sequence_parallel_mode: "zigzag-ring"