### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
# model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
template: deepseek_r1_distill_qwen

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# dataset: stop_predictor_dpo
# dataset: stop_predictor_dpo_no_early_stop_rejected_sample
dataset: omr_100k
# template: None
cutoff_len: 8192
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 0

### output
output_dir: saves/r1_llama_8B/sft_omr_100k
logging_steps: 1
save_steps: 100000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### sequence parallel
sequence_parallel_size: 4
sequence_parallel_mode: "zigzag-ring"